# Do not double-build branches and PRs from this repo
if: repo != head_repo

official-repo: &official-repo
  DanySK/LaTeX-Template-achemso
dist: focal
language: bash
git:
  depth: false
addons:
  apt:
    update: true
    packages:
    # LaTeX decent font processor
    - cm-super
    # For Minted
    - python-pygments
    # LaTeX
    - texlive-base
    - texlive-science
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-fonts-recommended
    # Debug
    - tree
env:
  global:
    - TERM="dumb"
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
install:
  - curl -s "https://get.sdkman.io" | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - sdk install kscript
script:
  - ./build.kts
after_failure:
  - tree -a
  - cat 0*/texput.log
before_deploy:
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - if [[ $(git describe) == *"-"* ]]; then git tag $(git describe) || :; fi
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
_deploy_base: &deploy_base
  provider: releases
  edge: true
  file: "*.pdf"
  on:
    repo: *official-repo
    tags: true

deploy:
  - <<: *deploy_base
  - <<: *deploy_base
    on:
      repo: *official-repo
      tags: false
